blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/your-username/StockFlow-Pro/wiki
    about: Check our documentation for common questions and setup guides
  - name: Discussions
    url: https://github.com/your-username/StockFlow-Pro/discussions
    about: Ask questions and discuss ideas with the community