name: UI Staging Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build UI (Docker)
        run: |
          docker build -f StockFlowPro.UI/Dockerfile -t ghcr.io/${{ github.repository_owner }}/stockflowpro-ui:staging .

      - name: Push UI Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/stockflowpro-ui:staging
